name: Ubuntu Tests

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  schedule:
#    - cron:  '0 9 * * 4'
  workflow_dispatch:
    inputs:
      build:
        default: true
        type: boolean
      docker:
        default: false
        type: boolean
      docker-standalone:
        default: false
        type: boolean

jobs:
  build:
    if: ${{ env.inputs.build }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: pip install --upgrade -r requirements.txt
    - name: fetch upstream cheat sheets
      run: python lib/fetch.py fetch-all
    - name: disable color
      run: |
        echo "CHTSH_QUERY_OPTIONS=\"T\"" >> ~/.cht.sh/cht.sh.conf
    - name: run bash tests
      run: bash tests/run-tests.sh
    - name: run pytest
      run: pytest lib/

  docker:
    if: ${{ env.inputs.docker }}  
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose build
    - run: docker images
    - run: |
        docker-compose -f docker-compose.yml up -d
        # docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d
        docker-compose ps
        # wait until the web server is up
        wget --timeout 3 --tries=5 --spider localhost:8002 2>&1 | grep -i http
        docker-compose logs --no-color
    - run: CHEATSH_TEST_STANDALONE=NO bash tests/run-tests.sh

  docker-standalone:
    if: ${{ env.inputs.docker-standalone }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose build
    - run: docker images
    - run: |
        docker-compose -f docker-compose.yml up -d
        # docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d
        docker-compose ps
        # wait until the web server is up
        wget --timeout 3 --tries=5 --spider localhost:8002 2>&1 | grep -i http
        docker-compose logs --no-color
    - run: CHEATSH_TEST_STANDALONE=YES bash tests/run-tests.sh
